apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: test
spec:
  compositeTypeRef:
    apiVersion: haarchri.io/v1alpha1
    kind: XTest
  mode: Pipeline
  pipeline:
  - step: render-templates
    functionRef:
      name: function-go-templating
    input:
      apiVersion: gotemplating.fn.crossplane.io/v1beta1
      kind: GoTemplate
      source: Inline
      inline:
        template: |
          {{- define "common-labels" -}}
          haarchri.io/account-name: {{ index .observed.composite.resource.metadata.labels "haarchri.io/account-name" }}
          haarchri.io/controlplane-name: {{ index .observed.composite.resource.metadata.labels "haarchri.io/controlplane-name" }}
          {{- end }}

          apiVersion: kubernetes.crossplane.io/v1alpha1
          kind: Object
          metadata:
            annotations:
              gotemplating.fn.crossplane.io/composition-resource-name: test
            labels:
              {{- include "common-labels" . | nindent 4}}
          spec:
            providerConfigRef:
              name: default
            forProvider:
              manifest:
                apiVersion: v1
                kind: ConfigMap
                metadata:
                  name: test-001
                  namespace: upbound-system
                  labels:
                    {{- include "common-labels" . | nindent 10}}
                data:
                  test: |
                    spec:
                      resources: []
  
  - step: ready
    functionRef:
      name: function-auto-ready
